server:
    servlet:
        context-path: /workshop
    port: 8080
spring:
    application:
        name: workshop7
    jackson:
        serialization:
            INDENT_OUTPUT: true
    datasource:
        url: jdbc:oracle:thin:@172.16.0.205:1521:TRIREF01
        username: COOP-2
        password: COOP-2
        driver-class-name: oracle.jdbc.OracleDriver
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update # ดูว่า table มีการเปลี่ยนแปลงไหม
            show-sql: true
    http:
        encoding:
            charset: UTF-8
            enabled: true
    servlet:
        multipart:
            max-request-size: 250MB
            max-file-size: 250MB
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
logging:
    level:
        com.ss.trainingspringboot: debug
